name: Smoke Testes - Schedule

on:
  schedule:
    -  cron: '2 16 * * 1-5'

jobs:
  RunTest:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o projeto
        uses: actions/checkout@v3

      - name: Instalar Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'maven'

      - name: Instalar Chrome
        uses: browser-actions/setup-chrome@v1
      - run: chrome --version

      - uses: nanasess/setup-chromedriver@v2
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: Run Test
        run: |
          mvn test -Dtest=RunCucumber -Dbrowser=chrome-ci

      - name: Gerar Relatorio
        if: always()
        run: mvn cluecumber-report:reporting

      - name: Arquivar relatorio
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: report-tests
          path: '**/formated-report/'
