name: Smoke Testes - PR

on:
   pull_request:
     branches: [ main ]

jobs:
  RunTest:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o projeto
        uses: actions/checkout@v3

      - name: Instalar Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'maven'

      - name: Instalar Chrome e Chromedriver
        uses: jamesmortensen/chromedriver-matcher-action@v1

      - name: Run Test
        run: | 
          mvn test -Dtest=RunCucumber -Dbrowser=chrome-ci

      - name: Gerar Relatorio
        run: mvn cluecumber-report:reporting

      - name: Arquivar relatorio
        uses: actions/upload-artifact@v3
        with:
          name: report-tests
          path: '**/formated-report/'
