name: Smoke Testes - PR

on:
   pull_request:
     branches: [ main ]

jobs:
  RunTest:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o projeto
        uses: actions/checkout@v3

      - name: Instalar Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'maven'

      - name: Instalar Chrome
        uses: browser-actions/setup-chrome@v1
      - run: chrome --version

      - uses: nanasess/setup-chromedriver@v2
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: Run Test
        run: |
          mvn test -Dtest=RunCucumber -Dbrowser=chrome-ci -Dcucumber.options="--tags @login-suscesso"
      - name: Gerar Relatorio
        if: always()
        run: mvn cluecumber-report:reporting

      - name: Arquivar relatorio
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: report-tests
          path: '**/formated-report/'

      - name: Enviar notificação Slack - Sucesso
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://img.icons8.com/color/48/pass.png
          SLACK_MESSAGE: 'Sucesso na execução de testes do PR :white_check_mark:'
          SLACK_USERNAME: SUCESSO

      - name: Enviar notificação Slack - Falha
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://img.icons8.com/color/48/fail.png
          SLACK_MESSAGE: 'Falha na execução de testes do PR :fire:'
          SLACK_USERNAME: FALHA